// js/rules.js

export const parameterRules = {
    blocklist: new Set([
        "utm_source",
        "utm_medium",
        "utm_campaign",
        "utm_term",
        "utm_content",
        "utm_id",
        "utm_source_platform",
        "fbclid",
        "gclid",
        "msclkid",
        "__s",
        "_hsenc",
        "_hsmi",
        "hsa_acc",
        "hsa_cam",
        "hsa_grp",
        "hsa_ad",
        "hsa_src",
        "hsa_tgt",
        "hsa_ver",
        "hsa_la",
        "hsa_ol",
        "mc_cid",
        "mc_eid",
        "mkt_tok",
        "vero_conv",
        "vero_id",
        "yclid",
    ]),
    referral: new Set([
        "ref",
        "refer",
        "affiliate",
        "aff",
        "invite",
        "referral",
        "referralCode",
        "friend",
        "via",
        "spm",
    ]),
    allowlist: {
        "youtube.com": new Set(["v", "t", "list", "index", "si"]),
        "youtu.be": new Set(["t", "si"]),
        "google.com": new Set(["q", "tbm", "tbs", "start", "uule"]),
        "amazon.com": new Set([
            "dp",
            "gp",
            "product",
            "keywords",
            "field-keywords",
        ]),
        "amazon.co.uk": new Set([
            "dp",
            "gp",
            "product",
            "keywords",
            "field-keywords",
        ]),
        "amazon.de": new Set([
            "dp",
            "gp",
            "product",
            "keywords",
            "field-keywords",
        ]),
        "amazon.ca": new Set([
            "dp",
            "gp",
            "product",
            "keywords",
            "field-keywords",
        ]),
        "amazon.jp": new Set([
            "dp",
            "gp",
            "product",
            "keywords",
            "field-keywords",
        ]),
        "reddit.com": new Set(["t"]),
        "duckduckgo.com": new Set(["q", "ia"]),
        "discord.gg": new Set(),
        "discord.com": new Set(["channel", "message"]),
    },
};
